### ISSUE TITLE
[nextjs-gh-pages] Possible issue with malformed `<title>` elements?

### ISSUE THREAD

**Issue by montchr** [kleinweb/logan-center#40]
I've been noticiing these warnings with `yarn workspace nextjs-gh-pages dev` running:

```console
wait  - compiling /podcast (client and server)...
event - compiled client and server successfully in 191 ms (1172 modules)
Warning: A title element received an array with more than 1 element as children. In browsers title Elements can only have Text Nodes as children. If the children being rendered output more thana single text node in aggregate the browser will display markup and comments as text in the title and hydration will likely fail and fall back to client rendering
    at title
    at head
    at Head (webpack-internal:///../../.yarn/__virtual__/next-virtual-eabdf9b921/5/.local/share/yarn/berry/cache/next-npm-13.0.2-b39abd22d0-9.zip/node_modules/next/dist/pages/_document.js:279:1)
    at html
    at Html (webpack-internal:///../../.yarn/__virtual__/next-virtual-eabdf9b921/5/.local/share/yarn/berry/cache/next-npm-13.0.2-b39abd22d0-9.zip/node_modules/next/dist/pages/_document.js:678:104)
    at Document
wait  - compiling...
event - compiled client and server successfully in 189 ms (1171 modules)
```

I haven't identified a cause -- nothing in the source code stuck out at me as problematic.

**Comment by montchr** [comment]
i haven't seen this recently -- may have been resolved since the move to a normal Next.js implementation on Vercel
